name: MongoDB Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Usar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    # Instalar dependencias del sistema necesarias
    - name: Instalar dependencias del sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl1.1 libcrypto++6
        sudo apt-get install -y libc++-dev libc++abi-dev

    - name: Instalar dependencias de Node.js
      run: |
        npm cache clean --force
        rm -rf node_modules
        rm -f package-lock.json
        npm install

    # Configurar variable de entorno para pruebas
    - name: Ejecutar pruebas
      run: npm test
      env:
        CI: true
        NODE_OPTIONS: --max_old_space_size=4096
